services:
  bdd:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"  # ⬅️ MySQL sur port 3306
    volumes:
      - db_data:/var/lib/mysql

  pma:
    image: phpmyadmin
    environment:
      PMA_HOST: bdd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"  # ⬅️ phpMyAdmin sur port 8080 (interface web)
    depends_on:
      - bdd

volumes:
  db_data: